import AppKit

final class ClipboardMonitor {
    private static let ignoredTypes = [
        "org.nspasteboard.TransientType",
        "org.nspasteboard.ConcealedType",
        "org.nspasteboard.AutoGeneratedType"
    ]

    private let pasteboard: NSPasteboard
    private let store: HistoryStore
    private var timer: Timer?
    private var lastChangeCount: Int

    init(store: HistoryStore, pasteboard: NSPasteboard = .general) {
        self.pasteboard = pasteboard
        self.store = store
        lastChangeCount = pasteboard.changeCount
    }

    func start() {
        timer = Timer.scheduledTimer(
            withTimeInterval: 0.35,
            repeats: true
        ) { [weak self] _ in
            self?.readIfChanged()
        }
        timer?.tolerance = 0.12
    }

    func stop() {
        timer?.invalidate()
        timer = nil
    }

    /// ClipTiny 自己写回剪贴板时调用，避免把刚粘贴的内容再记一遍。
    func acknowledgeOwnWrite(changeCount: Int) {
        lastChangeCount = max(lastChangeCount, changeCount)
    }

    func readIfChanged() {
        guard pasteboard.changeCount != lastChangeCount else { return }
        lastChangeCount = pasteboard.changeCount

        let currentTypes = Set((pasteboard.types ?? []).map(\.rawValue))
        guard currentTypes.isDisjoint(with: Self.ignoredTypes) else { return }

        if ClipboardImage.prefersImage(in: pasteboard) {
            if let capture = ClipboardImage.read(from: pasteboard) {
                store.add(capture)
            }
            return
        }
        guard let text = pasteboard.string(forType: .string) else { return }
        store.add(text)
    }
}
